### ISSUE TITLE
Change design of API server

### ISSUE THREAD

**Issue by jonathanhliu21** [jonyboi396825/COM-Server#104]
**Is your feature request related to a problem? Please describe.**
Someone might want to use the flask object for something else, such as rendering templates or making routes other than connection-related ones, and the current `RestApiHandler` makes it hard to do so.

**Describe the solution you'd like**
Make a new object `ConnectionServer` (?) (keep `RestApiHandler` for backward compatibility) that takes in both a (or several after #103?) `Connection` and a flask object so the user can still use the flask object later on. Then, add a `flask_restful` API attribute inside the `ConnectionServer` object and make the same methods as before. Also get rid of register/recall endpoints because solved in #83. Replace `RestApiHandler` with this class in CLI, and replace all `RestApiHandlers` in docs/getting started pages with this new class. 

For disconnecting, have one disconnect thread track all `Connection` objects instead of having multiple. (Maybe have a `MultiDisconnectTracker` (?) class in `disconnect.py`?)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jonyboi396825** [comment]
Also, get rid of the register/recall endpoints because these are already solved (#83).

**Comment by jonathanhliu21** [comment]
Multiple connections for one class not needed because multiple `ConnectionServer` objects can be used in just one flask server.
