### ISSUE TITLE
0.2 documentation issues

### ISSUE THREAD

**Issue by jonathanhliu21** [jonyboi396825/COM-Server#107]
# Closing because moving to private project. Open a new documentation issue to provide a documentation problem.

--- 

Provide all documentation ([develop version](https://com-server.readthedocs.io/en/latest/)) issues as comments below. These include
- Grammar errors
- Examples that do not work in the way indicated
- Confusing bits
- Formatting errors
- Anything else that seems off

# Docs todo

All docs issues will be organized as a todo list here.

**Bolded items** are items which I am not sure if I am going to implement. 

- [ ] clean up mkdocstrings config by adding globals in mkdocs.yml
- [ ] table of contents wrong
  - [ ] Delete functions, classes links, etc
- [ ] make sure all examples in getting started, library API, and custom IO thread are updated
- [ ] mention how to add custom delay at end of IO thread in custom_io_thread.md
- [ ] Fix getting data [here](https://com-server.readthedocs.io/en/develop/guide/getting-started/#receiving)
  - [ ] and full example below that
- [ ] For version 1 API, add section: "what happens if the serial device disconnects?"
- [ ] **To clear up confusion, on the library API, add `BaseConnection` methods to `Connection` with just the docstring and calling the `super()` method**
- [ ] Update links in root README and index.md server page (contributing and changelog, should be the ones in their version of documentation (or latest), not master branch) 
- [x] Update CONTRIBUTING.md (developing - the a new branch for a bugfix should be off the version branch, not master branch)
- [ ] Update shields for gh workflow status (should be branch tests) docs status 
- [ ] Change CONTRIBUTING.md virtualenv to be named `venv`

**Comment by jonyboi396825** [comment]
# Homepage

Table of contents
`com_server.disconnect_conns()` missing from Library API Table of Contents

**Comment by jonyboi396825** [comment]
### Library API

`receive_str` docs outdated
