### ISSUE TITLE
Remove 502 errors in builtin endpoints

### ISSUE THREAD

**Issue by jonyboi396825** [jonyboi396825/COM-Server#31]
**Is your feature request related to a problem? Please describe.**
Having 502 errors every time something failed to send can make  things hard to debug.

**Describe the solution you'd like**
When something fails to send, then the server should respond with 200 but have the message be different.

**Describe alternatives you've considered**
Add a "status" object that determines if something sent through or not.

**Additional context**
Werkzeug raises an exception every time there is a 500 error so it fills up the terminal screen.

**Comment by jonathanhliu21** [comment]
Removed breaking because it's going to go to v1 of built-in API
